version: "3.9"
services:
  # ========================================================================
  # Main development containers
  # ========================================================================
  node:
    build: ./build/development/node
    environment:
      - "NODE_ENV=development"
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    links:
      - mongodb
    depends_on:
      - mongodb
    command: "npm run start:dev"
    networks:
      - balance
    deploy:
      replicas: 2
      mode: replicated
      update_config:
        parallelism: 3
        delay: 10s
      restart_policy:
        condition: on-failure

  mongodb:
        image: mongo:latest
        container_name: "nest-mongo-db"
        environment:
          - MONGO_DATA_DIR=/var/mongo
          - MONGO_LOG_DIR=/dev/null
        volumes:
          - ./data/db:/data/db
        ports:
            - 27018:27017
        command: mongod --smallfiles --logpath=/dev/null # --quiet
networks:
  default:
    external:
      name: nest
  balance:
    driver: overlay
